### ISSUE TITLE
Nested layouts

### ISSUE THREAD

**Issue by betaWeb** [poppinss/edge#1]
Hi,

Is there a way to have nested layouts with sections ?

**Comment by RomainLanz** [comment]
Hey @betaWeb 👋 

Do you have an example?

Note: For those kind of questions, it would be better to use the forum now. https://forum.adonisjs.com/

**Comment by thetutlage** [comment]
Also nested layouts can never work. You must use components

**Comment by sharifzadesina** [comment]
We should be able to do like this:
```
auth.edge:
@layout('layouts.master')

@section('content')
h
@!section('othercontent')
f
@endsection
login.edge:
@layout('layouts.auth')

@section('othercontent')
test
@endsection
```
