### ISSUE TITLE
Support for IDE integration?

### ISSUE THREAD

**Issue by lelaw** [poppinss/edge#12]
Is anyone working on IDE/TextEditor integrations (or has it already been done) ?

**Comment by RomainLanz** [comment]
Hey @lelaw! 👋 

Yes, there's some integration already available.
Please check http://adonisjs.com/docs/4.0/views#_syntax_highlighting

**Comment by lelaw** [comment]
Thx @RomainLanz  
No love for Webstorm/IntelliJ Tho :(

**Comment by RomainLanz** [comment]
There's no support for IntelliJ platform for the moment.
You can read more here https://github.com/adonisjs/discussion/issues/46
