### ISSUE TITLE
[Docs] In 'Iteration' section should be reference to $parent

### ISSUE THREAD

**Issue by deromanenko** [poppinss/edge#15]
Stuck with impossibility of access to parent variables in Edge, like this:
```
@each(fabric in fabrics)
<h2>{{ fabric.name }} </h2>
	@each(product in products)
		@if(product.parent == fabric.id)
		<a href="/settings/product/{{product.id}}">{{ product.name }}</a>
		@endif
	@endeach
@endeach
```
Later on forum I got explanation that I should use `$parent.fabric.id`.
I came from Laravel world, where all variable accesible in all @foreach while it open. 

I more like Edge way with '$parent', it's more clear, but nowhere in documentation I can't find it. Can you add reference to '$parent' on 'Conditionals' page? Something called 'nested loops' maybe.

**Comment by thetutlage** [comment]
So this issue is more related to the concept missing in the docs, or you also facing the issue getting it worked?

**Comment by deromanenko** [comment]
Everything works great in code! 
Only thing to do is add some explanation to Edge docs, so the laravel-comers like me could quickly get into.

**Comment by thetutlage** [comment]
Sure, even if not coming from Laravel it should be in docs 😉
