### ISSUE TITLE
support async in added globals

### ISSUE THREAD

**Issue by nrempel** [poppinss/edge#16]
Hi there,

Is it possible to create globals that support coroutines?

for example:

```
edge.global('test', async function () {
  return await asyncFunc()
})
```

Thank you

**Comment by thetutlage** [comment]
The entire interface of `edge` is synchronous and hence it is not possible to call async methods inside it.

Also can be share what exactly are you trying to do?

**Comment by nrempel** [comment]
Hi @thetutlage,

I was creating a new global called `cssLoad` which loads the css from a file and inserts it directly in the html file in a `<style>` tag instead of creating a `<link>` tag for it.

I wanted to use `await fs.readFile` to read the file. Instead, I am now using `readFileSync` which works fine.

```
  View.global('cssLoad', function (path) {
    const cssPath = Helpers.publicPath(`${path}.css`)
    const file = fs.readFileSync(cssPath, { encoding: 'utf8' })
    return this.safe(`<style>\n${file}\n</style>`)
  })
```

**Comment by thetutlage** [comment]
I am not sure if you really want to do that in production ( for development it's fine ).

Like is there any benefit of inlining the CSS?

**Comment by nrempel** [comment]
I’m using this for rendering templates in html only. So in my environment, the html cannot reference external files.
It would be nice if I could run readFile asynchronously. Otherwise I will likely just write the css into he HTML file manually.
Are you open to pull requests to implement this?

On Sun, Dec 24, 2017 at 9:55 PM, Harminder Virk <notifications@github.com> wrote:
I am not sure if you really want to do that in production ( for development it's fine ).

Like is there any benefit of inlining the CSS?

**Comment by thetutlage** [comment]
@nrempel Nope, adding asynchronous support is way more work than it seems. 

1. It will be a breaking change.
2. Internal loops have to be async friendly.
3. Add support for `async/await` keyword within templates.

More than all the work, it is not something I want to add, since async templates are harder to debug.

Also as you said, inlining the css within your controller, or whatever code that renders the view is way to go

**Comment by nrempel** [comment]
Ah, ok. That does sounds like more effort than it’s worth.

I will find another way to inline the css.

Thank you!
