### ISSUE TITLE
Express  support? 

### ISSUE THREAD

**Issue by fanybook** [poppinss/edge#19]
will edge support Express?

**Comment by thetutlage** [comment]
Yes, edge is not found to any framework, you can use it with Express, Koa or whatever you want

**Comment by fanybook** [comment]
but, edge can't easy use via Express's 'view engine', because it don't implements __express method

**Comment by RomainLanz** [comment]
Create your own wrapper. https://expressjs.com/en/advanced/developing-template-engines.html

**Comment by ecrmnn** [comment]
@fanybook I needed this too and ended up creating an Express wrapper.
It even overrides the render function to that you can reference your views with dot notation.

➡️ https://github.com/ecrmnn/express-edge
