### ISSUE TITLE
Declare variable

### ISSUE THREAD

**Issue by alithestar2000** [poppinss/edge#26]
Hi Virk,

If this platform is wrong then I appologise in advance. Right now i am confused about how to declare a variable in edge.js. like say i want to declare  a variable named "i" and then want to increment in a loop. how to do it?

**Comment by thetutlage** [comment]
Can you please share some code?

**Comment by alithestar2000** [comment]
var i = 0;
                  @each(u in users_data)
                    <tr>
                      <td>{{i = i + 1}}</td>
                      <td>{{ u ? u.username: ''}}</td>
                      <td class='wait'></td>
                      <td>
                        <a class="btn btn-primary btn-sm" href='customer_friend_list?cid='+u.username> Friends</a>
                      </td>  
                      <td>
                        <a class="btn btn-danger btn-sm user_del" href='#' _id=u.username> Remove</a>
                      </td>  
                    </tr>    
                  @endeach

**Comment by RomainLanz** [comment]
Why you aren't using the `$loop.index` variable?

http://edge.adonisjs.com/docs/iteration#_loop_variable

**Comment by alithestar2000** [comment]
@RomainLanz thank you so much. it's a gr8 answer. I have now what i wanted.

Now just a private question. I was using Jade previously but some hurdles forced me to find some other template engine. Since I am myself a php developer and know laravel. I just get a chance to work with node. My question is: whether edge.js a complete templating solution. My project is at the start. can i carry this big project with edge.js?

Thanks in advance.

**Comment by thetutlage** [comment]
@alithestar2000 It depends on your definition of complete.

I believe by browsing the docs, you can get much of the idea on what all Edge supports and feel free to ask questions around it on the forum https://forum.adonisjs.com/

**Comment by alithestar2000** [comment]
@thetutlage  thank you. I feel now that you have strong belief in this so i can continue with this.
