### ISSUE TITLE
E_INVALID_EXPRESSION

### ISSUE THREAD

**Issue by WeyIin** [poppinss/edge#3]
appending content to a master layout using `@!section('content')` works fine, however using `@!section('content') ` (notice the whitespace AFTER closing parenthesis?) throws an error:

> InvalidExpressionException
> 
> E_INVALID_EXPRESSION: Invalid expression <'content') > passed to (section) `block`

I was looking for hours as of why it didn't work, while following edge docs closely.

**Comment by thetutlage** [comment]
Yup seems like an issue with the compiler. I never faced it coz I use `.editorconfig` file with a rule to trim extra space. 

But will fix it
