### ISSUE TITLE
Adding global

### ISSUE THREAD

**Issue by garciamarco33** [poppinss/edge#31]
Hello,
Where am I supposed to add global ?
I'm rendering the view in my controller with
`return view.render('menu/main')`

**Comment by RomainLanz** [comment]
Hey @garciamarco33! 👋 

You seems to be inside an Adonis application.
Follow the link bellow to get the documentation about this feature.

http://adonisjs.com/docs/4.1/views#_globals_2

**Comment by garciamarco33** [comment]
I was looking in the edge documentation, my bad and thank you !
