### ISSUE TITLE
nested each

### ISSUE THREAD

**Issue by macOneOone** [poppinss/edge#32]
Why a parent variable of the first each returns undefined?

I have this code right here:
<img width="824" alt="captura de ecra 2018-03-13 as 14 05 31" src="https://user-images.githubusercontent.com/16170629/37343549-2919f544-26c8-11e8-8a2e-efd486096475.png">

And when my code run it returns this:

<img width="1429" alt="captura de ecra 2018-03-13 as 14 13 16" src="https://user-images.githubusercontent.com/16170629/37343744-c742660c-26c8-11e8-882c-dcebafb5d877.png">

Post data (variable post)
<img width="854" alt="captura de ecra 2018-03-13 as 14 15 05" src="https://user-images.githubusercontent.com/16170629/37343839-04dcc624-26c9-11e8-96f5-ca98193e8c7f.png">

Flag data
<img width="1440" alt="captura de ecra 2018-03-13 as 14 16 16" src="https://user-images.githubusercontent.com/16170629/37343906-2ba08444-26c9-11e8-9cff-24a04d15e9bb.png">

**Comment by RomainLanz** [comment]
Hey @macOneOone! 👋 

Please take a look to https://github.com/poppinss/edge/issues/30

**Comment by macOneOone** [comment]
Thanks.

This should be on the document lol 👍 
<img width="791" alt="captura de ecra 2018-03-13 as 17 34 45" src="https://user-images.githubusercontent.com/16170629/37355784-dc2370cc-26e4-11e8-9886-ac6e868c8923.png">
