### ISSUE TITLE
can't use variable from components params on each function

### ISSUE THREAD

**Issue by macOneOone** [poppinss/edge#33]
Hey friend,

I've this code
``
@each(item in flags)
    @!components('components/bullet',els=item)
@endeach
``
and in my components i've 
``
@each(el in els)
    {{el.token}}
@endeach
``

When i run this code, the information is that i'm using nothing is happen. Could you explain me why is that?

**Comment by thetutlage** [comment]
Can you post proper code, since `@components` is not a tag and also there is no ending block for `@component`
