### ISSUE TITLE
section blocks in strings?

### ISSUE THREAD

**Issue by imperez** [poppinss/edge#35]
So in Nunjucks I was able to do something like this....

layout
`<div class="main-content {% block classes %}{% endblock %}"></div>`

This allowed me to do this in a child template
`{% block classes %}container is-about{% endblock %}`

It's a tiny example but it was definitely helpful for keeping view specific settings outside of the controller. This doesn't work with @section blocks. Would this be something that you want to look to add?

**Comment by thetutlage** [comment]
I didn't understand what you mean by `{% block classes %}`, can you please try to reiterate yourself?

**Comment by imperez** [comment]
Sorry for the late response I didn't get the notification for your reply.

Basically I want to be able to use a @section tag in a string as below. This way in a child template I can refer to that block and set whatever value is needed. I was able to do it in Nunjucks in Adonis 3 but I can't seem to do it correctly in edge.

`<div class="main-content @section('classes')@endsection"></div>`

**Comment by thetutlage** [comment]
A section is block that contains content. How can A block be used as a class?. What you need is a simple variable

```
<div class="main-content {{ classes }}"></div>
```

**Comment by imperez** [comment]
Ok thanks for the clarification. I was hoping to avoid having that type of logic in the controller but it’s no big deal.

**Comment by thetutlage** [comment]
Not sure what you are trying to achieve, but you can set a local variable and use it as classes

```
@set('classes', 'foo bar')
<div class="main-content {{ classes }}"></div>
```

**Comment by imperez** [comment]
Yup I saw in another issue that I can use the @set method. Just to give some context on how I was trying to setup my views.

My layout.edge would look like this....
`
<html>
    <head>
        <title>@section('title')@endsection</title>
    </head>
    <body>
        <div class="main-content @section('classes')@endsection">
            @section('content')
            @endsection
        </div>
    </body>
</html>
`

Then in my child view I wanted to structure it as so...
`@layout('layout')

@section('title')My Wonderful Homepage@endsection
@section('classes')container-fluid@endsection

@section('content)
    <h1>Hello World</h1>
@endsection`

Now normally I would use a CMS and store things like title or classes in the database. I just haven't gotten to that point yet. So to keep things clean and not put so much view logic in controllers I wanted to try and set things up as above. 

It doesn't seem like edge works that way. It's no big deal since I can update my code to use variables as suggested. I just wanted to give you an example of what I was trying to do.

**Comment by RomainLanz** [comment]
Hey @imperez! 👋 

What's your issue of using `@set` and then the following code?

```html
<html>
    <head>
        <title{{ title }}</title>
    </head>
    <body>
        <div class="main-content {{ classes }}">
            @section('content')
            @endsection
        </div>
    </body>
</html>
```

**Comment by imperez** [comment]
The problem is since the `classes` and `title` values will change page to page you will have to put in logic in layout.edge to set those variables based on home vs about such as below.

```
@if(page == 'home')
    @set('title', 'homepage')
    @set('classes', 'container-fluid')
@elseif(page == 'about')
    @set('title', 'about')
    @set('classes', 'container')
@endif

<html>
    <head>
        <title{{ title }}</title>
    </head>
    <body>
        <div class="main-content {{ classes }}">
            @section('content')
            @endsection
        </div>
    </body>
</html>
```

Now if I were to use `@section` blocks then it's easier to maintain since I can set up my child views as below. It keeps my layout simple and my child views has the data that applies to it.m.  

```
// home
@layout('layout')

@section('title')My Wonderful Homepage@endsection
@section('classes')container-fluid@endsection

@section('content)
    <h1>Hello World</h1>
@endsection
```

```
// about
@layout('layout')

@section('title')About@endsection
@section('classes')container@endsection

@section('content)
    <h1>About</h1>
@endsection
```

It sounds like this is not the intended use for section blocks. That's fine since I think my use case is very specific.

**Comment by RomainLanz** [comment]
I believe you misunderstand how this works.
You can directly set your variables inside your child templates.
```
@layout('layout')

@section('content)
    @set('title', 'My Wonderful Homepage')
    @set('classes', 'container-fluid')
    <h1>Hello World</h1>
@endsection
```

**Comment by imperez** [comment]
Oh wow I didn’t know that was actually possible. Thanks for letting me know since I think your solution works better.

**Comment by thetutlage** [comment]
Closing since answered
