### ISSUE TITLE
Visual Studio Code syntax

### ISSUE THREAD

**Issue by vabatta** [poppinss/edge#36]
Hi,

I would like to know if it's planned to have the Syntax Highlighting plugin also for Visual Studio Code, as AdonisJS development seems to be great also with that IDE.

**Comment by thetutlage** [comment]
I believe there’s already one, just search for Edge

**Comment by alinnert** [comment]
Yes, here it is: https://marketplace.visualstudio.com/items?itemName=luongnd.edge

**Comment by thetutlage** [comment]
@alinnert Thanks for sharing the link. Closing the issue
