### ISSUE TITLE
Using each in each to access the values of each of the top each

### ISSUE THREAD

**Issue by emirhanengn** [poppinss/edge#43]
Hello!

I have two codes for each. In the second each, I want to access the values of the first each. But it doesn't. Returns undefined.

Thanks!

**Comment by RomainLanz** [comment]
Hey !

Please, do a little search before asking a question. 😄 

- https://github.com/poppinss/edge/issues/32
- https://github.com/poppinss/edge/issues/30

**Comment by emirhanengn** [comment]
So sorry! Thanks for answering!! :)
