### ISSUE TITLE
[question] Is there anyway to reload a @component whith jquery?

### ISSUE THREAD

**Issue by asantamarian** [poppinss/edge#47]
Is there anyway to reload a @component with jquery? sorry if its a noob question.

**Comment by RomainLanz** [comment]
Hey @asantamarian! 👋 

Edge is server-side rendered, that means your frontend code doesn't even know about it.
You need to use a frontend framework like React, Vue, Stimulus or whatever do handle this.

**Comment by thetutlage** [comment]
As @RomainLanz said, Edge templates are rendered on server, So jQuery of any frontend Javascript cannot control them.
