### ISSUE TITLE
Modulo operation

### ISSUE THREAD

**Issue by jbrhinalyn** [poppinss/edge#50]
Hi.

Is there a way for modulo operation?
Thanks.

**Comment by jbrhinalyn** [comment]
Hi Sir. Yes sure.
Here is some piece of code that im trying working to.

@if(announcements != '')
					<div class="row">
						{{ cnt = 1 }}
						@each(announcement in announcements)
							<div class="col-lg-4 col-md-12">
								<div class="ts-service-box">
									<div class="ts-service-image-wrapper">
										<img class="img-fluid" src="{{ announcement.image }}" alt="{{ announcement.title }}">
									</div>
									<div class="ts-service-content">
										<h3 class="service-title">{{ announcement.title }}</h3>
										{{ el(announcement.content) }}
									</div>
								</div>
							</div>
							@if(cnt % 3 == 0)
								</div>
								<div class="row">
							@elseif(cnt == total_announcements)
								</div>
							@endif
							{{ cnt++ }}
						@endeach
				@endif

**Comment by thetutlage** [comment]
Can you please format your codeblock properly? Also `{{ cnt = 1 }}` is not a valid syntax, you cannot mutate values in templates like this, you need to use the following.

```
@set('cnt', 1)
```

**Comment by thetutlage** [comment]
Closing since not actionable
