### ISSUE TITLE
Nested loops lose access to iterator values

### ISSUE THREAD

**Issue by tomcss** [poppinss/edge#52]
Example:

    @each(day in range(7))
        @each(hour in range(9,17))
            {{ day }}:{{ hour }}
        @endeach
    @endeach

Gives the following result
`:9 :10 :11 :12 :13 :14 :15 :16 :9 :10 :11 :12 :13 :14 :15 :16 :9 :10 :11 :12 :13 :14 :15 :16 :9 :10 :11 :12 :13 :14 :15 :16 :9 :10 :11 :12 :13 :14 :15 :16 :9 :10 :11 :12 :13 :14 :15 :16 :9 :10 :11 :12 :13 :14 :15 :16 `

When I was really expecting:
`0:9 0:10 0:12 0:13... 1:9 1:10 ... 6:15, 6:16`

I couldn't find anything in the documents to suggest how the engine is supposed to manage nested loops, but I would expect the outer iterator value to remain accessible in inner loops.

**Comment by RomainLanz** [comment]
Hey @tomcss ! 👋 

You need to use `$parent`.

See:
- #32 
- #30
