### ISSUE TITLE
format an integer to 2 decimal places inside the edge template

### ISSUE THREAD

**Issue by jbrhinalyn** [poppinss/edge#55]
Hi. I have a question. It is possible to format an floating point value into 2 decimal places? example output is 45.6785 and it should be display as 45.68.

**Comment by thetutlage** [comment]
Create a global method, that does `parseFloat` for you.

```
View.global('parseFloat', function (value, decimal) {
 return parseFloat(value).toFixed(decimal)
})
```

And use it as

```
{{ parseFloat(45.6785, 2) }}
```

**Comment by jbrhinalyn** [comment]
Thanks @thetutlage . it works bro. Highly appreciated.
