### ISSUE TITLE
Dynamic object properties name not working

### ISSUE THREAD

**Issue by egodasa** [poppinss/edge#58]
```
const headers = ['username', 'password']
...

view :
@each(user in users)
  {{ user['username'] }} // Working
  {{ user.username }} // Working
  
  @each(header in headers)
    user[header]  // Not Working, return undefined value
  @endeach
@endeach
```
Am I missing something?

**Comment by egodasa** [comment]
Using `$parent` on nested each. So, the right code is `$parent.user[header]`

**Comment by RomainLanz** [comment]
Hey @egodasa! 👋 

You need to use `$parent`.
Please so some search before posting an issue.

See:
- https://github.com/poppinss/edge/issues/52
- https://github.com/poppinss/edge/issues/32 	 
- https://github.com/poppinss/edge/issues/30

**Comment by egodasa** [comment]
@RomainLanz I've read the documentation and forgot about `$parent` variable. Using search bar isn't helpful since I'm looking for "Dynamic Properties" name, not "nested each".

Thx for Your suggestion. I'm still learning english. Sorry if I have some mistake.
