### ISSUE TITLE
Extending layout not working as expected

### ISSUE THREAD

**Issue by adamlc** [poppinss/edge#6]
When extended a layout some of the sections dont appear later in the final template.

In the following example the content section doesn't get rendered, as I would expect.

```
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">

    <title>Title</title>

    <meta http-equiv="X-UA-Compatible" content="IE=Edge,chrome=1">
    <meta name="viewport" content="width=device-width, initial-scale=1, maximum-scale=1">
</head>
<body>
        @!section('content')

        @!section('footer')
</body>
</html>
```

Then an extended layout:

```
@layout('layouts/master')

@section('footer')
    <h2>footer content</h2>
@endsection
```

Then I have the actual page / template:

```
@layout('layouts/extended-layout')

@section('content')
CONTENT HERE DOESNT APPEAR
@endsection
```

**Comment by RomainLanz** [comment]
Hey @adamlc ! 👋 

As a side note, you should change your composition with the following.

*master.edge*
```html
<!DOCTYPE html>
<html>
<head>
  <meta charset="UTF-8">
  <!-- ... -->
</head>
<body>
  @!section('page')
</body>
</html>
```

*app.edge*
```html
@layout('master')

@section('page')
  @include('_header')

  <main>
    @!section('content')
  </main>
  
  @include('_footer')
@endsection
```

*your-page.edge*
```html
@section('content')
  <!-- ... -->
@endsection
```

**Comment by thetutlage** [comment]
I am not in favor of nested layouts at all. It just makes the entire composition of views complex. Having 2 separate layout files is fine and for re-usability, we can create `partials`.

**Comment by thetutlage** [comment]
Since I haven't heard from anyone. I will think of it as no change in the codebase for now. Thanks 😄
